// Singkatan resmi per kitab (slug → abbreviation)
export const BOOK_ABBR: Record<string, string> = {
  // ── Perjanjian Lama ────────────────────────────────────────────────────────
  "kejadian":         "Kej",
  "keluaran":         "Kel",
  "imamat":           "Im",
  "bilangan":         "Bil",
  "ulangan":          "Ul",
  "yosua":            "Yos",
  "hakim-hakim":      "Hak",
  "rut":              "Rut",
  "1-samuel":         "1Sam",
  "2-samuel":         "2Sam",
  "1-raja-raja":      "1Raj",
  "2-raja-raja":      "2Raj",
  "1-tawarikh":       "1Taw",
  "2-tawarikh":       "2Taw",
  "ezra":             "Ezr",
  "nehemia":          "Neh",
  "ester":            "Est",
  "ayub":             "Ayb",
  "mazmur":           "Mzm",
  "amsal":            "Ams",
  "pengkhotbah":      "Pkh",
  "kidung-agung":     "Kid",
  "yesaya":           "Yes",
  "yeremia":          "Yer",
  "ratapan":          "Rat",
  "yehezkiel":        "Yeh",
  "daniel":           "Dan",
  "hosea":            "Hos",
  "yoel":             "Yoel",
  "amos":             "Am",
  "obaja":            "Ob",
  "yunus":            "Yun",
  "mikha":            "Mi",
  "nahum":            "Nah",
  "habakuk":          "Hab",
  "zefanya":          "Zef",
  "hagai":            "Hag",
  "zakharia":         "Zak",
  "maleakhi":         "Mal",
  // ── Perjanjian Baru ────────────────────────────────────────────────────────
  "matius":           "Mat",
  "markus":           "Mrk",
  "lukas":            "Luk",
  "yohanes":          "Yoh",
  "kisah-para-rasul": "Kis",
  "roma":             "Rm",
  "1-korintus":       "1Kor",
  "2-korintus":       "2Kor",
  "galatia":          "Gal",
  "efesus":           "Ef",
  "filipi":           "Flp",
  "kolose":           "Kol",
  "1-tesalonika":     "1Tes",
  "2-tesalonika":     "2Tes",
  "1-timotius":       "1Tim",
  "2-timotius":       "2Tim",
  "titus":            "Tit",
  "filemon":          "Flm",
  "ibrani":           "Ibr",
  "yakobus":          "Yak",
  "1-petrus":         "1Pet",
  "2-petrus":         "2Pet",
  "1-yohanes":        "1Yoh",
  "2-yohanes":        "2Yoh",
  "3-yohanes":        "3Yoh",
  "yudas":            "Yud",
  "wahyu":            "Why",
};

export function getAbbr(slug: string): string {
  return BOOK_ABBR[slug] ?? slug.slice(0, 3);
}
